<a href="https://colab.research.google.com/github/MukeshSiddh/ML-AME/blob/main/Copy_of_Assignment_1A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
import numpy as np
arr1= np.array([1,2,3,4,5,6,7,8])

# Create a 2-dimensional NumPy array using np.array()
arr2= np.array([[1,2,3,4],[5,6,7,8]])

# Create a 3-dimensional Numpy array using np.array()
arr3=arr1.reshape(2,2,2)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
arr1.shape

(8,)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1.ndim

1

In [ ]:
arr1.size

8

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
# Attributes of 2-dimensional array
arr2.shape

(2, 4)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr2.size

8

In [ ]:
arr2.ndim

2

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
# Attributes of 3-dimensional array
arr3.shape

(2, 2, 2)

In [ ]:
arr3.ndim

3

In [ ]:
arr3.dtype

dtype('int64')

In [ ]:
arr3.size

8

In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(arr1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8

In [ ]:
# Create an array of shape (10, 2) with only ones
from numpy import random
arr=random.choice([1],size=(10,2))
arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
import numpy as np
ar=np.zeros((7, 2, 3),dtype=np.int64)
ar

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3
print(np.arange(0,100,3))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a=random.randint(10,size=(7,2))
a

array([[7, 2],
       [6, 6],
       [7, 3],
       [3, 3],
       [5, 9],
       [6, 3],
       [9, 0]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random.rand(3,5)

array([[0.67834282, 0.21191725, 0.50463072, 0.97901457, 0.18686303],
       [0.81803594, 0.05907703, 0.28851504, 0.7173205 , 0.64408647],
       [0.61407635, 0.15833793, 0.62361596, 0.30756059, 0.43809128]])

In [ ]:
# Set the random seed to 42
random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random.randint(10,size=(4,6))

array([[9, 4, 0, 1, 9, 0],
       [1, 8, 9, 0, 8, 6],
       [4, 3, 0, 4, 6, 8],
       [1, 8, 4, 1, 3, 6]])

Run the cell above again, what happens?
We get same array every time.

Are the numbers in the array different or the same? Why do think this is?
Yes,The seed() method is used to initialize the random number generator.

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rar=random.randint(1,10, size=(3,7))
rar

# Find the unique numbers in the array you just created
#np.unique(rar)

array([[6, 2, 9, 1, 6, 9, 6],
       [8, 9, 6, 9, 2, 6, 2],
       [5, 8, 8, 8, 8, 7, 1]])

In [ ]:
# Find the 0'th index of the latest array you created
rar[0][0]

6

In [ ]:
# Get the first 2 rows of latest array you created
x=rar[0:2,0:7]
x

array([[6, 2, 9, 1, 6, 9, 6],
       [8, 9, 6, 9, 2, 6, 2]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
rar[0:2,0:2]

array([[6, 2],
       [8, 9]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arrr=random.randint(10,size=(3,5))
arro= np.ones((3,5))
arrr

array([[4, 6, 4, 9, 8],
       [0, 7, 1, 7, 1],
       [1, 5, 5, 0, 8]])

In [ ]:
# Add the two arrays together
arrr+arro

array([[ 5.,  7.,  5., 10.,  9.],
       [ 1.,  8.,  2.,  8.,  2.],
       [ 2.,  6.,  6.,  1.,  9.]])

In [ ]:
# Create another array of ones of shape (5, 3)
arro1=np.ones((5,3))

In [ ]:
# Try add the array of ones and the other most recent array together
arro+arro1

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?
size are different

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
arro2=np.ones((3,5))

In [ ]:
# Subtract the new array of ones from the other most recent array
arro2-arro

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Multiply the ones array with the latest array
arrr*arro

array([[4., 6., 4., 9., 8.],
       [0., 7., 1., 7., 1.],
       [1., 5., 5., 0., 8.]])

In [ ]:
# Take the latest array to the power of 2 using '**'
arrr**2

array([[16, 36, 16, 81, 64],
       [ 0, 49,  1, 49,  1],
       [ 1, 25, 25,  0, 64]])

In [ ]:
# Do the same thing with np.square()
arrl=np.square(arrr)
arrl

array([[16, 36, 16, 81, 64],
       [ 0, 49,  1, 49,  1],
       [ 1, 25, 25,  0, 64]])

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(arrl)

28.533333333333335

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(arrl)

81

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(arrl)

0

In [ ]:
# Find the standard deviation of the latest array
np.std(arrl)

26.33594923715912

In [ ]:
# Find the variance of the latest array
np.var(arrl)

693.5822222222221

In [ ]:
# Reshape the latest array to (3, 5, 1)
arrl.reshape(3,5,1)

array([[[16],
        [36],
        [16],
        [81],
        [64]],

       [[ 0],
        [49],
        [ 1],
        [49],
        [ 1]],

       [[ 1],
        [25],
        [25],
        [ 0],
        [64]]])

In [ ]:
# Transpose the latest array
np.transpose(arrl)

array([[16,  0,  1],
       [36, 49, 25],
       [16,  1, 25],
       [81, 49,  0],
       [64,  1, 64]])

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1=random.randint(10,size=(3,3))
a2=random.randint(10,size=(3,2))
a2

array([[3, 6],
       [0, 0],
       [6, 5]])

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[15, 23],
       [42, 49],
       [ 6,  5]])

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3=random.randint(10,size=(4,3))
a4=random.randint(10,size=(4,3))

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(a3,a4)

ValueError: ignored

It doesn't work. How would you fix it?
tranpose one of them


In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
a5=np.transpose(a4)
np.dot(a3,a5)

array([[ 45,  90,  90,  81],
       [116, 138, 184, 117],
       [ 28,  30,  30,  30],
       [ 97,  93,  99,  93]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a3=random.randint(10,size=(4,3))
a4=random.randint(10,size=(4,3))

In [ ]:
# Compare the two arrays with '>'
a3>a4

array([[False, False, False],
       [False,  True, False],
       [ True, False, False],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
a3>=a4

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [ True,  True,  True]])

In [ ]:
# Find which elements of the first array are greater than 7
a3>7

array([[False, False, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False]])

In [ ]:
# Which parts of each array are equal? (try using '==')
a3==a4

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(a3)

array([[0, 0, 1],
       [1, 4, 9],
       [0, 1, 9],
       [3, 7, 9]])

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(a3)

array([[0, 2, 1],
       [0, 2, 1],
       [1, 2, 0],
       [2, 0, 1]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a3)

4

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a3)

0

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a3,axis=1)

array([1, 1, 0, 1])

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a3,axis=0)

array([0, 2, 0])

In [ ]:
# Create an array of normally distributed random numbers
random.normal(size=(3,3))

array([[ 0.56682536, -1.34028558,  1.18058023],
       [-0.51458875,  1.12954814,  0.44856744],
       [-1.01042473, -0.95004281,  0.63256036]])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.